// TODO: Remove this file when API or local storage is integrated
export const GroceryData = [
    { id: 1, itemLabel: 'Apples', quantity: '1 Kg' },
    { id: 2, itemLabel: 'Bananas', quantity: '6 pieces' },
    { id: 3, itemLabel: 'Carrots', quantity: '500 g' },
    { id: 4, itemLabel: 'Tomatoes', quantity: '1 Kg' },
    { id: 5, itemLabel: 'Potatoes', quantity: '2 Kg' },
    { id: 6, itemLabel: 'Onions', quantity: '1.5 Kg' },
    { id: 7, itemLabel: 'Milk', quantity: '2 Liters' },
    { id: 8, itemLabel: 'Bread', quantity: '1 loaf' },
    { id: 9, itemLabel: 'Eggs', quantity: '12 pieces' },
    { id: 10, itemLabel: 'Chicken Breast', quantity: '1 Kg' },
    { id: 11, itemLabel: 'Rice', quantity: '5 Kg' },
    { id: 12, itemLabel: 'Pasta', quantity: '1 Kg' },
    { id: 13, itemLabel: 'Cheese', quantity: '250 g' },
    { id: 14, itemLabel: 'Spinach', quantity: '1 bunch' },
    { id: 15, itemLabel: 'Yogurt', quantity: '1 Liter' },
    { id: 16, itemLabel: 'Orange Juice', quantity: '1 Liter' },
    { id: 17, itemLabel: 'Butter', quantity: '200 g' },
    { id: 18, itemLabel: 'Salt', quantity: '500 g' },
    { id: 19, itemLabel: 'Sugar', quantity: '1 Kg' },
    { id: 20, itemLabel: 'Black Pepper', quantity: '100 g' },
    { id: 21, itemLabel: 'Garlic', quantity: '200 g' },
    { id: 22, itemLabel: 'Cucumber', quantity: '1 Kg' },
    { id: 23, itemLabel: 'Lettuce', quantity: '1 head' },
    { id: 24, itemLabel: 'Bell Peppers', quantity: '500 g' },
    { id: 25, itemLabel: 'Mangoes', quantity: '3 pieces' },
    { id: 26, itemLabel: 'Strawberries', quantity: '500 g' },
    { id: 27, itemLabel: 'Blueberries', quantity: '250 g' },
    { id: 28, itemLabel: 'Almonds', quantity: '200 g' },
    { id: 29, itemLabel: 'Cashews', quantity: '200 g' },
    { id: 30, itemLabel: 'Peanut Butter', quantity: '1 jar' },
    { id: 31, itemLabel: 'Honey', quantity: '250 g' },
    { id: 32, itemLabel: 'Olive Oil', quantity: '500 ml' },
    { id: 33, itemLabel: 'Vinegar', quantity: '250 ml' },
    { id: 34, itemLabel: 'Soy Sauce', quantity: '300 ml' },
    { id: 35, itemLabel: 'Coffee', quantity: '250 g' },
    { id: 36, itemLabel: 'Tea Bags', quantity: '50 bags' },
    { id: 37, itemLabel: 'Chocolate', quantity: '100 g' },
    { id: 38, itemLabel: 'Ice Cream', quantity: '1 tub' },
    { id: 39, itemLabel: 'Frozen Peas', quantity: '1 Kg' },
    { id: 40, itemLabel: 'Frozen Corn', quantity: '1 Kg' },
    { id: 41, itemLabel: 'Cereal', quantity: '500 g' },
    { id: 42, itemLabel: 'Oats', quantity: '1 Kg' },
    { id: 43, itemLabel: 'Flour', quantity: '2 Kg' },
    { id: 44, itemLabel: 'Baking Powder', quantity: '100 g' },
    { id: 45, itemLabel: 'Yeast', quantity: '50 g' },
    { id: 46, itemLabel: 'Chili Powder', quantity: '100 g' },
    { id: 47, itemLabel: 'Cinnamon', quantity: '100 g' },
    { id: 48, itemLabel: 'Coconut Milk', quantity: '400 ml' },
    { id: 49, itemLabel: 'Tuna', quantity: '2 cans' }
];