// TODO: Remove this file when API or local storage is integrated
export const GroceryData = [
    { itemLabel: 'Apples', quantity: '1 Kg' },
    { itemLabel: 'Bananas', quantity: '6 pieces' },
    { itemLabel: 'Carrots', quantity: '500 g' },
    { itemLabel: 'Tomatoes', quantity: '1 Kg' },
    { itemLabel: 'Potatoes', quantity: '2 Kg' },
    { itemLabel: 'Onions', quantity: '1.5 Kg' },
    { itemLabel: 'Milk', quantity: '2 Liters' },
    { itemLabel: 'Bread', quantity: '1 loaf' },
    { itemLabel: 'Eggs', quantity: '12 pieces' },
    { itemLabel: 'Chicken Breast', quantity: '1 Kg' },
    { itemLabel: 'Rice', quantity: '5 Kg' },
    { itemLabel: 'Pasta', quantity: '1 Kg' },
    { itemLabel: 'Cheese', quantity: '250 g' },
    { itemLabel: 'Spinach', quantity: '1 bunch' },
    { itemLabel: 'Yogurt', quantity: '1 Liter' },
    { itemLabel: 'Orange Juice', quantity: '1 Liter' },
    { itemLabel: 'Butter', quantity: '200 g' },
    { itemLabel: 'Salt', quantity: '500 g' },
    { itemLabel: 'Sugar', quantity: '1 Kg' },
    { itemLabel: 'Black Pepper', quantity: '100 g' },
    { itemLabel: 'Garlic', quantity: '200 g' },
    { itemLabel: 'Cucumber', quantity: '1 Kg' },
    { itemLabel: 'Lettuce', quantity: '1 head' },
    { itemLabel: 'Bell Peppers', quantity: '500 g' },
    { itemLabel: 'Mangoes', quantity: '3 pieces' },
    { itemLabel: 'Strawberries', quantity: '500 g' },
    { itemLabel: 'Blueberries', quantity: '250 g' },
    { itemLabel: 'Almonds', quantity: '200 g' },
    { itemLabel: 'Cashews', quantity: '200 g' },
    { itemLabel: 'Peanut Butter', quantity: '1 jar' },
    { itemLabel: 'Honey', quantity: '250 g' },
    { itemLabel: 'Olive Oil', quantity: '500 ml' },
    { itemLabel: 'Vinegar', quantity: '250 ml' },
    { itemLabel: 'Soy Sauce', quantity: '300 ml' },
    { itemLabel: 'Coffee', quantity: '250 g' },
    { itemLabel: 'Tea Bags', quantity: '50 bags' },
    { itemLabel: 'Chocolate', quantity: '100 g' },
    { itemLabel: 'Ice Cream', quantity: '1 tub' },
    { itemLabel: 'Frozen Peas', quantity: '1 Kg' },
    { itemLabel: 'Frozen Corn', quantity: '1 Kg' },
    { itemLabel: 'Cereal', quantity: '500 g' },
    { itemLabel: 'Oats', quantity: '1 Kg' },
    { itemLabel: 'Flour', quantity: '2 Kg' },
    { itemLabel: 'Baking Powder', quantity: '100 g' },
    { itemLabel: 'Yeast', quantity: '50 g' },
    { itemLabel: 'Chili Powder', quantity: '100 g' },
    { itemLabel: 'Cinnamon', quantity: '100 g' },
    { itemLabel: 'Coconut Milk', quantity: '400 ml' },
    { itemLabel: 'Tuna', quantity: '2 cans' }
];