// TODO: Remove this file when API or local storage is integrated
export const GroceryData = [
    { id: '1', name: 'Apples', quantity: '1 Kg', synced: true, shared: false },
    { id: '2', name: 'Bananas', quantity: '6 pieces', synced: true, shared: false },
    { id: '3', name: 'Carrots', quantity: '500 g', synced: true, shared: false },
    { id: '4', name: 'Tomatoes', quantity: '1 Kg', synced: true, shared: false },
    { id: '5', name: 'Potatoes', quantity: '2 Kg', synced: true, shared: false },
    { id: '6', name: 'Onions', quantity: '1.5 Kg', synced: true, shared: false },
    { id: '7', name: 'Milk', quantity: '2 Liters', synced: true, shared: false },
    { id: '8', name: 'Bread', quantity: '1 loaf', synced: true, shared: false },
    { id: '9', name: 'Eggs', quantity: '12 pieces', synced: true, shared: false },
    { id: '10', name: 'Chicken Breast', quantity: '1 Kg', synced: true, shared: false },
    { id: '11', name: 'Rice', quantity: '5 Kg', synced: true, shared: false },
    { id: '12', name: 'Pasta', quantity: '1 Kg', synced: true, shared: false },
    { id: '13', name: 'Cheese', quantity: '250 g', synced: true, shared: false },
    { id: '14', name: 'Spinach', quantity: '1 bunch', synced: true, shared: false },
    { id: '15', name: 'Yogurt', quantity: '1 Liter', synced: true, shared: false },
    { id: '16', name: 'Orange Juice', quantity: '1 Liter', synced: true, shared: false },
    { id: '17', name: 'Butter', quantity: '200 g', synced: true, shared: false },
    { id: '18', name: 'Salt', quantity: '500 g', synced: true, shared: false },
    { id: '19', name: 'Sugar', quantity: '1 Kg', synced: true, shared: false },
    { id: '20', name: 'Black Pepper', quantity: '100 g', synced: true, shared: false },
    { id: '21', name: 'Garlic', quantity: '200 g', synced: true, shared: false },
    { id: '22', name: 'Cucumber', quantity: '1 Kg', synced: true, shared: false },
    { id: '23', name: 'Lettuce', quantity: '1 head', synced: true, shared: false },
    { id: '24', name: 'Bell Peppers', quantity: '500 g', synced: true, shared: false },
    { id: '25', name: 'Mangoes', quantity: '3 pieces', synced: true, shared: false },
    { id: '26', name: 'Strawberries', quantity: '500 g', synced: true, shared: false },
    { id: '27', name: 'Blueberries', quantity: '250 g', synced: true, shared: false },
    { id: '28', name: 'Almonds', quantity: '200 g', synced: true, shared: false },
    { id: '29', name: 'Cashews', quantity: '200 g', synced: true, shared: false },
    { id: '30', name: 'Peanut Butter', quantity: '1 jar', synced: true, shared: false },
    { id: '31', name: 'Honey', quantity: '250 g', synced: true, shared: false },
    { id: '32', name: 'Olive Oil', quantity: '500 ml', synced: true, shared: false },
    { id: '33', name: 'Vinegar', quantity: '250 ml', synced: true, shared: false },
    { id: '34', name: 'Soy Sauce', quantity: '300 ml', synced: true, shared: false },
    { id: '35', name: 'Coffee', quantity: '250 g', synced: true, shared: false },
    { id: '36', name: 'Tea Bags', quantity: '50 bags', synced: true, shared: false },
    { id: '37', name: 'Chocolate', quantity: '100 g', synced: true, shared: false },
    { id: '38', name: 'Ice Cream', quantity: '1 tub', synced: true, shared: false },
    { id: '39', name: 'Frozen Peas', quantity: '1 Kg', synced: true, shared: false },
    { id: '40', name: 'Frozen Corn', quantity: '1 Kg', synced: true, shared: false },
    { id: '41', name: 'Cereal', quantity: '500 g', synced: true, shared: false },
    { id: '42', name: 'Oats', quantity: '1 Kg', synced: true, shared: false },
    { id: '43', name: 'Flour', quantity: '2 Kg', synced: true, shared: false },
    { id: '44', name: 'Baking Powder', quantity: '100 g', synced: true, shared: false },
    { id: '45', name: 'Yeast', quantity: '50 g', synced: true, shared: false },
    { id: '46', name: 'Chili Powder', quantity: '100 g', synced: true, shared: false },
    { id: '47', name: 'Cinnamon', quantity: '100 g', synced: true, shared: false },
    { id: '48', name: 'Coconut Milk', quantity: '400 ml', synced: true, shared: false },
    { id: '49', name: 'Tuna', quantity: '2 cans', synced: true, shared: false },
    { id: '50', name: 'Salmon', quantity: '500 g', synced: true, shared: false },
    { id: '51', name: 'Shrimp', quantity: '300 g', synced: true, shared: false },
    { id: '52', name: 'Cod', quantity: '400 g', synced: true, shared: false },
    { id: '53', name: 'Lemon', quantity: '4 pieces', synced: true, shared: false },
    { id: '54', name: 'Lime', quantity: '6 pieces', synced: true, shared: false },
    { id: '55', name: 'Avocado', quantity: '3 pieces', synced: true, shared: false },
    { id: '56', name: 'Broccoli', quantity: '1 head', synced: true, shared: false },
    { id: '57', name: 'Cauliflower', quantity: '1 head', synced: true, shared: false },
    { id: '58', name: 'Cabbage', quantity: '1 head', synced: true, shared: false },
    { id: '59', name: 'Zucchini', quantity: '500 g', synced: true, shared: false },
    { id: '60', name: 'Eggplant', quantity: '1 piece', synced: true, shared: false },
    { id: '61', name: 'Mushrooms', quantity: '300 g', synced: true, shared: false },
    { id: '62', name: 'Asparagus', quantity: '250 g', synced: true, shared: false },
    { id: '63', name: 'Green Beans', quantity: '500 g', synced: true, shared: false },
    { id: '64', name: 'Brussels Sprouts', quantity: '400 g', synced: true, shared: false },
    { id: '65', name: 'Sweet Potato', quantity: '1 Kg', synced: true, shared: false },
    { id: '66', name: 'Beets', quantity: '500 g', synced: true, shared: false },
    { id: '67', name: 'Radishes', quantity: '200 g', synced: true, shared: false },
    { id: '68', name: 'Celery', quantity: '1 bunch', synced: true, shared: false },
    { id: '69', name: 'Corn', quantity: '4 ears', synced: true, shared: false },
    { id: '70', name: 'Pumpkin', quantity: '1 Kg', synced: true, shared: false },
    { id: '71', name: 'Butternut Squash', quantity: '1 Kg', synced: true, shared: false },
    { id: '72', name: 'Kale', quantity: '1 bunch', synced: true, shared: false },
    { id: '73', name: 'Arugula', quantity: '100 g', synced: true, shared: false },
    { id: '74', name: 'Basil', quantity: '1 pot', synced: true, shared: false },
    { id: '75', name: 'Parsley', quantity: '1 bunch', synced: true, shared: false },
    { id: '76', name: 'Cilantro', quantity: '1 bunch', synced: true, shared: false },
    { id: '77', name: 'Dill', quantity: '1 bunch', synced: true, shared: false },
    { id: '78', name: 'Rosemary', quantity: '1 bunch', synced: true, shared: false },
    { id: '79', name: 'Thyme', quantity: '1 bunch', synced: true, shared: false },
    { id: '80', name: 'Oregano', quantity: '50 g', synced: true, shared: false },
    { id: '81', name: 'Paprika', quantity: '100 g', synced: true, shared: false },
    { id: '82', name: 'Cumin', quantity: '100 g', synced: true, shared: false },
    { id: '83', name: 'Turmeric', quantity: '100 g', synced: true, shared: false },
    { id: '84', name: 'Ginger', quantity: '200 g', synced: true, shared: false },
    { id: '85', name: 'Cardamom', quantity: '50 g', synced: true, shared: false },
    { id: '86', name: 'Cloves', quantity: '50 g', synced: true, shared: false },
    { id: '87', name: 'Nutmeg', quantity: '50 g', synced: true, shared: false },
    { id: '88', name: 'Bay Leaves', quantity: '20 leaves', synced: true, shared: false },
    { id: '89', name: 'Vanilla Extract', quantity: '100 ml', synced: true, shared: false },
    { id: '90', name: 'Coconut Oil', quantity: '500 ml', synced: true, shared: false },
    { id: '91', name: 'Sesame Oil', quantity: '250 ml', synced: true, shared: false },
    { id: '92', name: 'Sunflower Oil', quantity: '1 Liter', synced: true, shared: false },
    { id: '93', name: 'Canola Oil', quantity: '1 Liter', synced: true, shared: false },
    { id: '94', name: 'Balsamic Vinegar', quantity: '250 ml', synced: true, shared: false },
    { id: '95', name: 'Apple Cider Vinegar', quantity: '500 ml', synced: true, shared: false },
    { id: '96', name: 'White Wine Vinegar', quantity: '250 ml', synced: true, shared: false },
    { id: '97', name: 'Red Wine Vinegar', quantity: '250 ml', synced: true, shared: false },
    { id: '98', name: 'Worcestershire Sauce', quantity: '150 ml', synced: true, shared: false },
    { id: '99', name: 'Hot Sauce', quantity: '200 ml', synced: true, shared: false },
    { id: '100', name: 'Ketchup', quantity: '500 ml', synced: true, shared: false },
    { id: '101', name: 'Mustard', quantity: '250 ml', synced: true, shared: false },
    { id: '102', name: 'Mayonnaise', quantity: '400 ml', synced: true, shared: false },
    { id: '103', name: 'Ranch Dressing', quantity: '250 ml', synced: true, shared: false },
    { id: '104', name: 'Italian Dressing', quantity: '250 ml', synced: true, shared: false },
    { id: '105', name: 'Caesar Dressing', quantity: '250 ml', synced: true, shared: false },
    { id: '106', name: 'Beef', quantity: '1 Kg', synced: true, shared: false },
    { id: '107', name: 'Pork', quantity: '800 g', synced: true, shared: false },
    { id: '108', name: 'Lamb', quantity: '600 g', synced: true, shared: false },
    { id: '109', name: 'Ground Beef', quantity: '500 g', synced: true, shared: false },
    { id: '110', name: 'Ground Turkey', quantity: '500 g', synced: true, shared: false },
    { id: '111', name: 'Chicken Thighs', quantity: '1 Kg', synced: true, shared: false },
    { id: '112', name: 'Chicken Wings', quantity: '800 g', synced: true, shared: false },
    { id: '113', name: 'Turkey Breast', quantity: '600 g', synced: true, shared: false },
    { id: '114', name: 'Duck', quantity: '1 whole', synced: true, shared: false },
    { id: '115', name: 'Bacon', quantity: '300 g', synced: true, shared: false },
    { id: '116', name: 'Ham', quantity: '500 g', synced: true, shared: false },
    { id: '117', name: 'Sausages', quantity: '400 g', synced: true, shared: false },
    { id: '118', name: 'Pepperoni', quantity: '200 g', synced: true, shared: false },
    { id: '119', name: 'Salami', quantity: '200 g', synced: true, shared: false },
    { id: '120', name: 'Prosciutto', quantity: '150 g', synced: true, shared: false },
    { id: '121', name: 'Cheddar Cheese', quantity: '300 g', synced: true, shared: false },
    { id: '122', name: 'Mozzarella Cheese', quantity: '300 g', synced: true, shared: false },
    { id: '123', name: 'Parmesan Cheese', quantity: '200 g', synced: true, shared: false },
    { id: '124', name: 'Swiss Cheese', quantity: '200 g', synced: true, shared: false },
    { id: '125', name: 'Gouda Cheese', quantity: '200 g', synced: true, shared: false },
    { id: '126', name: 'Brie Cheese', quantity: '150 g', synced: true, shared: false },
    { id: '127', name: 'Camembert Cheese', quantity: '150 g', synced: true, shared: false },
    { id: '128', name: 'Blue Cheese', quantity: '150 g', synced: true, shared: false },
    { id: '129', name: 'Feta Cheese', quantity: '200 g', synced: true, shared: false },
    { id: '130', name: 'Goat Cheese', quantity: '150 g', synced: true, shared: false },
    { id: '131', name: 'Cream Cheese', quantity: '200 g', synced: true, shared: false },
    { id: '132', name: 'Cottage Cheese', quantity: '500 g', synced: true, shared: false },
    { id: '133', name: 'Ricotta Cheese', quantity: '250 g', synced: true, shared: false },
    { id: '134', name: 'Greek Yogurt', quantity: '500 g', synced: true, shared: false },
    { id: '135', name: 'Sour Cream', quantity: '250 g', synced: true, shared: false },
    { id: '136', name: 'Heavy Cream', quantity: '500 ml', synced: true, shared: false },
    { id: '137', name: 'Half and Half', quantity: '500 ml', synced: true, shared: false },
    { id: '138', name: 'Buttermilk', quantity: '500 ml', synced: true, shared: false },
    { id: '139', name: 'Almond Milk', quantity: '1 Liter', synced: true, shared: false },
    { id: '140', name: 'Soy Milk', quantity: '1 Liter', synced: true, shared: false },
    { id: '141', name: 'Coconut Milk', quantity: '1 Liter', synced: true, shared: false },
    { id: '142', name: 'Oat Milk', quantity: '1 Liter', synced: true, shared: false },
    { id: '143', name: 'Rice Milk', quantity: '1 Liter', synced: true, shared: false },
    { id: '144', name: 'Quinoa', quantity: '500 g', synced: true, shared: false },
    { id: '145', name: 'Barley', quantity: '500 g', synced: true, shared: false },
    { id: '146', name: 'Bulgur', quantity: '500 g', synced: true, shared: false },
    { id: '147', name: 'Couscous', quantity: '500 g', synced: true, shared: false },
    { id: '148', name: 'Polenta', quantity: '500 g', synced: true, shared: false },
    { id: '149', name: 'Buckwheat', quantity: '500 g', synced: true, shared: false },
    { id: '150', name: 'Millet', quantity: '500 g', synced: true, shared: false },
    { id: '151', name: 'Amaranth', quantity: '500 g', synced: true, shared: false },
    { id: '152', name: 'Chia Seeds', quantity: '200 g', synced: true, shared: false },
    { id: '153', name: 'Flax Seeds', quantity: '200 g', synced: true, shared: false },
    { id: '154', name: 'Sunflower Seeds', quantity: '200 g', synced: true, shared: false },
    { id: '155', name: 'Pumpkin Seeds', quantity: '200 g', synced: true, shared: false },
    { id: '156', name: 'Sesame Seeds', quantity: '200 g', synced: true, shared: false },
    { id: '157', name: 'Walnuts', quantity: '200 g', synced: true, shared: false },
    { id: '158', name: 'Pecans', quantity: '200 g', synced: true, shared: false },
    { id: '159', name: 'Hazelnuts', quantity: '200 g', synced: true, shared: false },
    { id: '160', name: 'Brazil Nuts', quantity: '200 g', synced: true, shared: false },
    { id: '161', name: 'Pistachios', quantity: '200 g', synced: true, shared: false },
    { id: '162', name: 'Macadamia Nuts', quantity: '200 g', synced: true, shared: false },
    { id: '163', name: 'Pine Nuts', quantity: '100 g', synced: true, shared: false },
    { id: '164', name: 'Coconut Flakes', quantity: '200 g', synced: true, shared: false },
    { id: '165', name: 'Dried Cranberries', quantity: '200 g', synced: true, shared: false },
    { id: '166', name: 'Raisins', quantity: '200 g', synced: true, shared: false },
    { id: '167', name: 'Dried Apricots', quantity: '200 g', synced: true, shared: false },
    { id: '168', name: 'Dried Figs', quantity: '200 g', synced: true, shared: false },
    { id: '169', name: 'Dates', quantity: '200 g', synced: true, shared: false },
    { id: '170', name: 'Prunes', quantity: '200 g', synced: true, shared: false },
    { id: '171', name: 'Lentils', quantity: '500 g', synced: true, shared: false },
    { id: '172', name: 'Chickpeas', quantity: '500 g', synced: true, shared: false },
    { id: '173', name: 'Black Beans', quantity: '500 g', synced: true, shared: false },
    { id: '174', name: 'Kidney Beans', quantity: '500 g', synced: true, shared: false },
    { id: '175', name: 'Navy Beans', quantity: '500 g', synced: true, shared: false },
    { id: '176', name: 'Pinto Beans', quantity: '500 g', synced: true, shared: false },
    { id: '177', name: 'Lima Beans', quantity: '500 g', synced: true, shared: false },
    { id: '178', name: 'Green Peas', quantity: '500 g', synced: true, shared: false },
    { id: '179', name: 'Split Peas', quantity: '500 g', synced: true, shared: false },
    { id: '180', name: 'Black Eyed Peas', quantity: '500 g', synced: true, shared: false },
    { id: '181', name: 'Pears', quantity: '1 Kg', synced: true, shared: false },
    { id: '182', name: 'Peaches', quantity: '1 Kg', synced: true, shared: false },
    { id: '183', name: 'Plums', quantity: '500 g', synced: true, shared: false },
    { id: '184', name: 'Cherries', quantity: '500 g', synced: true, shared: false },
    { id: '185', name: 'Grapes', quantity: '1 Kg', synced: true, shared: false },
    { id: '186', name: 'Kiwi', quantity: '6 pieces', synced: true, shared: false },
    { id: '187', name: 'Pineapple', quantity: '1 whole', synced: true, shared: false },
    { id: '188', name: 'Papaya', quantity: '1 whole', synced: true, shared: false },
    { id: '189', name: 'Watermelon', quantity: '1 whole', synced: true, shared: false },
    { id: '190', name: 'Cantaloupe', quantity: '1 whole', synced: true, shared: false },
    { id: '191', name: 'Honeydew', quantity: '1 whole', synced: true, shared: false },
    { id: '192', name: 'Pomegranate', quantity: '2 pieces', synced: true, shared: false },
    { id: '193', name: 'Coconut', quantity: '1 whole', synced: true, shared: false },
    { id: '194', name: 'Passion Fruit', quantity: '4 pieces', synced: true, shared: false },
    { id: '195', name: 'Dragon Fruit', quantity: '2 pieces', synced: true, shared: false },
    { id: '196', name: 'Star Fruit', quantity: '3 pieces', synced: true, shared: false },
    { id: '197', name: 'Lychee', quantity: '200 g', synced: true, shared: false },
    { id: '198', name: 'Rambutan', quantity: '200 g', synced: true, shared: false },
    { id: '199', name: 'Durian', quantity: '1 piece', synced: true, shared: false },
    { id: '200', name: 'Jackfruit', quantity: '1 Kg', synced: true, shared: false },
    { id: '201', name: 'Whole Wheat Bread', quantity: '1 loaf', synced: true, shared: false },
    { id: '202', name: 'Sourdough Bread', quantity: '1 loaf', synced: true, shared: false },
    { id: '203', name: 'Rye Bread', quantity: '1 loaf', synced: true, shared: false },
    { id: '204', name: 'Pumpernickel Bread', quantity: '1 loaf', synced: true, shared: false },
    { id: '205', name: 'Bagels', quantity: '6 pieces', synced: true, shared: false },
    { id: '206', name: 'English Muffins', quantity: '6 pieces', synced: true, shared: false },
    { id: '207', name: 'Croissants', quantity: '4 pieces', synced: true, shared: false },
    { id: '208', name: 'Pita Bread', quantity: '1 pack', synced: true, shared: false },
    { id: '209', name: 'Naan Bread', quantity: '4 pieces', synced: true, shared: false },
    { id: '210', name: 'Tortillas', quantity: '1 pack', synced: true, shared: false },
    { id: '211', name: 'Corn Tortillas', quantity: '1 pack', synced: true, shared: false },
    { id: '212', name: 'Crackers', quantity: '1 box', synced: true, shared: false },
    { id: '213', name: 'Graham Crackers', quantity: '1 box', synced: true, shared: false },
    { id: '214', name: 'Pretzels', quantity: '200 g', synced: true, shared: false },
    { id: '215', name: 'Popcorn', quantity: '100 g', synced: true, shared: false },
    { id: '216', name: 'Chips', quantity: '200 g', synced: true, shared: false },
    { id: '217', name: 'Corn Chips', quantity: '200 g', synced: true, shared: false },
    { id: '218', name: 'Rice Cakes', quantity: '1 pack', synced: true, shared: false },
    { id: '219', name: 'Granola Bars', quantity: '1 box', synced: true, shared: false },
    { id: '220', name: 'Protein Bars', quantity: '1 box', synced: true, shared: false },
    { id: '221', name: 'Energy Bars', quantity: '1 box', synced: true, shared: false },
    { id: '222', name: 'Trail Mix', quantity: '300 g', synced: true, shared: false },
    { id: '223', name: 'Granola', quantity: '500 g', synced: true, shared: false },
    { id: '224', name: 'Muesli', quantity: '500 g', synced: true, shared: false },
    { id: '225', name: 'Instant Oatmeal', quantity: '1 box', synced: true, shared: false },
    { id: '226', name: 'Cornflakes', quantity: '500 g', synced: true, shared: false },
    { id: '227', name: 'Bran Flakes', quantity: '500 g', synced: true, shared: false },
    { id: '228', name: 'Rice Krispies', quantity: '500 g', synced: true, shared: false },
    { id: '229', name: 'Cheerios', quantity: '500 g', synced: true, shared: false },
    { id: '230', name: 'Frosted Flakes', quantity: '500 g', synced: true, shared: false },
    { id: '231', name: 'Pancake Mix', quantity: '500 g', synced: true, shared: false },
    { id: '232', name: 'Waffle Mix', quantity: '500 g', synced: true, shared: false },
    { id: '233', name: 'Muffin Mix', quantity: '500 g', synced: true, shared: false },
    { id: '234', name: 'Cake Mix', quantity: '500 g', synced: true, shared: false },
    { id: '235', name: 'Brownie Mix', quantity: '500 g', synced: true, shared: false },
    { id: '236', name: 'Cookie Mix', quantity: '500 g', synced: true, shared: false },
    { id: '237', name: 'Bread Mix', quantity: '500 g', synced: true, shared: false },
    { id: '238', name: 'Pizza Dough', quantity: '500 g', synced: true, shared: false },
    { id: '239', name: 'Pie Crust', quantity: '2 pieces', synced: true, shared: false },
    { id: '240', name: 'Puff Pastry', quantity: '2 sheets', synced: true, shared: false },
    { id: '241', name: 'Phyllo Dough', quantity: '1 pack', synced: true, shared: false },
    { id: '242', name: 'Tomato Sauce', quantity: '500 ml', synced: true, shared: false },
    { id: '243', name: 'Marinara Sauce', quantity: '500 ml', synced: true, shared: false },
    { id: '244', name: 'Alfredo Sauce', quantity: '400 ml', synced: true, shared: false },
    { id: '245', name: 'Pesto Sauce', quantity: '200 ml', synced: true, shared: false },
    { id: '246', name: 'BBQ Sauce', quantity: '350 ml', synced: true, shared: false },
    { id: '247', name: 'Teriyaki Sauce', quantity: '250 ml', synced: true, shared: false },
    { id: '248', name: 'Stir Fry Sauce', quantity: '250 ml', synced: true, shared: false },
    { id: '249', name: 'Fish Sauce', quantity: '200 ml', synced: true, shared: false },
    { id: '250', name: 'Oyster Sauce', quantity: '200 ml', synced: true, shared: false },
    { id: '251', name: 'Hoisin Sauce', quantity: '200 ml', synced: true, shared: false },
    { id: '252', name: 'Sweet and Sour Sauce', quantity: '250 ml', synced: true, shared: false },
    { id: '253', name: 'Curry Paste', quantity: '100 g', synced: true, shared: false },
    { id: '254', name: 'Tomato Paste', quantity: '200 g', synced: true, shared: false },
    { id: '255', name: 'Coconut Cream', quantity: '400 ml', synced: true, shared: false },
    { id: '256', name: 'Broth - Chicken', quantity: '1 Liter', synced: true, shared: false },
    { id: '257', name: 'Broth - Beef', quantity: '1 Liter', synced: true, shared: false },
    { id: '258', name: 'Broth - Vegetable', quantity: '1 Liter', synced: true, shared: false },
    { id: '259', name: 'Coconut Water', quantity: '1 Liter', synced: true, shared: false },
    { id: '260', name: 'Sparkling Water', quantity: '1 Liter', synced: true, shared: false },
    { id: '261', name: 'Lemonade', quantity: '1 Liter', synced: true, shared: false },
    { id: '262', name: 'Iced Tea', quantity: '1 Liter', synced: true, shared: false },
    { id: '263', name: 'Sports Drink', quantity: '1 Liter', synced: true, shared: false },
    { id: '264', name: 'Energy Drink', quantity: '500 ml', synced: true, shared: false },
    { id: '265', name: 'Soda - Cola', quantity: '2 Liters', synced: true, shared: false },
    { id: '266', name: 'Soda - Sprite', quantity: '2 Liters', synced: true, shared: false },
    { id: '267', name: 'Soda - Orange', quantity: '2 Liters', synced: true, shared: false },
    { id: '268', name: 'Apple Juice', quantity: '1 Liter', synced: true, shared: false },
    { id: '269', name: 'Grape Juice', quantity: '1 Liter', synced: true, shared: false },
    { id: '270', name: 'Cranberry Juice', quantity: '1 Liter', synced: true, shared: false },
    { id: '271', name: 'Pomegranate Juice', quantity: '1 Liter', synced: true, shared: false },
    { id: '272', name: 'Tomato Juice', quantity: '1 Liter', synced: true, shared: false },
    { id: '273', name: 'V8 Juice', quantity: '1 Liter', synced: true, shared: false },
    { id: '274', name: 'Green Tea', quantity: '50 bags', synced: true, shared: false },
    { id: '275', name: 'Black Tea', quantity: '50 bags', synced: true, shared: false },
    { id: '276', name: 'Herbal Tea', quantity: '50 bags', synced: true, shared: false },
    { id: '277', name: 'Chamomile Tea', quantity: '30 bags', synced: true, shared: false },
    { id: '278', name: 'Peppermint Tea', quantity: '30 bags', synced: true, shared: false },
    { id: '279', name: 'Earl Grey Tea', quantity: '30 bags', synced: true, shared: false },
    { id: '280', name: 'Coffee Beans', quantity: '500 g', synced: true, shared: false },
    { id: '281', name: 'Instant Coffee', quantity: '200 g', synced: true, shared: false },
    { id: '282', name: 'Espresso', quantity: '250 g', synced: true, shared: false },
    { id: '283', name: 'Decaf Coffee', quantity: '250 g', synced: true, shared: false },
    { id: '284', name: 'Coffee Filters', quantity: '100 pieces', synced: true, shared: false },
    { id: '285', name: 'Coffee Creamer', quantity: '500 ml', synced: true, shared: false },
    { id: '286', name: 'Whipped Cream', quantity: '250 ml', synced: true, shared: false },
    { id: '287', name: 'Marshmallows', quantity: '200 g', synced: true, shared: false },
    { id: '288', name: 'Chocolate Chips', quantity: '200 g', synced: true, shared: false },
    { id: '289', name: 'Dark Chocolate', quantity: '200 g', synced: true, shared: false },
    { id: '290', name: 'White Chocolate', quantity: '200 g', synced: true, shared: false },
    { id: '291', name: 'Milk Chocolate', quantity: '200 g', synced: true, shared: false },
    { id: '292', name: 'Cocoa Powder', quantity: '200 g', synced: true, shared: false },
    { id: '293', name: 'Powdered Sugar', quantity: '500 g', synced: true, shared: false },
    { id: '294', name: 'Brown Sugar', quantity: '500 g', synced: true, shared: false },
    { id: '295', name: 'Maple Syrup', quantity: '250 ml', synced: true, shared: false },
    { id: '296', name: 'Agave Nectar', quantity: '250 ml', synced: true, shared: false },
    { id: '297', name: 'Corn Syrup', quantity: '250 ml', synced: true, shared: false },
    { id: '298', name: 'Molasses', quantity: '250 ml', synced: true, shared: false },
    { id: '299', name: 'Jam - Strawberry', quantity: '300 g', synced: true, shared: false },
    { id: '300', name: 'Jam - Raspberry', quantity: '300 g', synced: true, shared: false },
    { id: '301', name: 'Jam - Apricot', quantity: '300 g', synced: true, shared: false },
    { id: '302', name: 'Marmalade', quantity: '300 g', synced: true, shared: false },
    { id: '303', name: 'Nutella', quantity: '400 g', synced: true, shared: false },
    { id: '304', name: 'Almond Butter', quantity: '300 g', synced: true, shared: false },
    { id: '305', name: 'Cashew Butter', quantity: '300 g', synced: true, shared: false },
    { id: '306', name: 'Sunflower Seed Butter', quantity: '300 g', synced: true, shared: false },
    { id: '307', name: 'Tahini', quantity: '250 g', synced: true, shared: false },
    { id: '308', name: 'Hummus', quantity: '300 g', synced: true, shared: false },
    { id: '309', name: 'Guacamole', quantity: '200 g', synced: true, shared: false },
    { id: '310', name: 'Salsa', quantity: '400 g', synced: true, shared: false },
    { id: '311', name: 'Pickles', quantity: '500 g', synced: true, shared: false },
    { id: '312', name: 'Olives - Green', quantity: '300 g', synced: true, shared: false },
    { id: '313', name: 'Olives - Black', quantity: '300 g', synced: true, shared: false },
    { id: '314', name: 'Capers', quantity: '100 g', synced: true, shared: false },
    { id: '315', name: 'Sun-dried Tomatoes', quantity: '200 g', synced: true, shared: false },
    { id: '316', name: 'Roasted Red Peppers', quantity: '300 g', synced: true, shared: false },
    { id: '317', name: 'Artichoke Hearts', quantity: '300 g', synced: true, shared: false },
    { id: '318', name: 'Hearts of Palm', quantity: '300 g', synced: true, shared: false },
    { id: '319', name: 'Bamboo Shoots', quantity: '400 g', synced: true, shared: false },
    { id: '320', name: 'Water Chestnuts', quantity: '300 g', synced: true, shared: false },
    { id: '321', name: 'Canned Corn', quantity: '400 g', synced: true, shared: false },
    { id: '322', name: 'Canned Beans', quantity: '400 g', synced: true, shared: false },
    { id: '323', name: 'Canned Tomatoes', quantity: '400 g', synced: true, shared: false },
    { id: '324', name: 'Canned Peas', quantity: '400 g', synced: true, shared: false },
    { id: '325', name: 'Canned Carrots', quantity: '400 g', synced: true, shared: false },
    { id: '326', name: 'Canned Spinach', quantity: '400 g', synced: true, shared: false },
    { id: '327', name: 'Canned Pumpkin', quantity: '400 g', synced: true, shared: false },
    { id: '328', name: 'Canned Peaches', quantity: '400 g', synced: true, shared: false },
    { id: '329', name: 'Canned Pears', quantity: '400 g', synced: true, shared: false },
    { id: '330', name: 'Canned Pineapple', quantity: '400 g', synced: true, shared: false },
    { id: '331', name: 'Canned Coconut Milk', quantity: '400 ml', synced: true, shared: false },
    { id: '332', name: 'Sardines', quantity: '2 cans', synced: true, shared: false },
    { id: '333', name: 'Anchovies', quantity: '100 g', synced: true, shared: false },
    { id: '334', name: 'Smoked Salmon', quantity: '200 g', synced: true, shared: false },
    { id: '335', name: 'Crab Meat', quantity: '200 g', synced: true, shared: false },
    { id: '336', name: 'Lobster Meat', quantity: '200 g', synced: true, shared: false },
    { id: '337', name: 'Frozen Shrimp', quantity: '500 g', synced: true, shared: false },
    { id: '338', name: 'Frozen Fish Fillets', quantity: '500 g', synced: true, shared: false },
    { id: '339', name: 'Frozen Berries', quantity: '500 g', synced: true, shared: false },
    { id: '340', name: 'Frozen Mango', quantity: '500 g', synced: true, shared: false },
    { id: '341', name: 'Frozen Strawberries', quantity: '500 g', synced: true, shared: false },
    { id: '342', name: 'Frozen Blueberries', quantity: '500 g', synced: true, shared: false },
    { id: '343', name: 'Frozen Raspberries', quantity: '500 g', synced: true, shared: false },
    { id: '344', name: 'Frozen Blackberries', quantity: '500 g', synced: true, shared: false },
    { id: '345', name: 'Frozen Cherries', quantity: '500 g', synced: true, shared: false },
    { id: '346', name: 'Frozen Peaches', quantity: '500 g', synced: true, shared: false },
    { id: '347', name: 'Frozen Broccoli', quantity: '500 g', synced: true, shared: false },
    { id: '348', name: 'Frozen Cauliflower', quantity: '500 g', synced: true, shared: false },
    { id: '349', name: 'Frozen Green Beans', quantity: '500 g', synced: true, shared: false },
    { id: '350', name: 'Frozen Spinach', quantity: '500 g', synced: true, shared: false },
    { id: '351', name: 'Frozen Mixed Vegetables', quantity: '500 g', synced: true, shared: false },
    { id: '352', name: 'Frozen Stir Fry Mix', quantity: '500 g', synced: true, shared: false },
    { id: '353', name: 'Frozen Pizza', quantity: '1 piece', synced: true, shared: false },
    { id: '354', name: 'Frozen Lasagna', quantity: '1 piece', synced: true, shared: false },
    { id: '355', name: 'Frozen Burritos', quantity: '4 pieces', synced: true, shared: false },
    { id: '356', name: 'Frozen Waffles', quantity: '8 pieces', synced: true, shared: false },
    { id: '357', name: 'Frozen Pancakes', quantity: '8 pieces', synced: true, shared: false },
    { id: '358', name: 'Frozen French Fries', quantity: '1 Kg', synced: true, shared: false },
    { id: '359', name: 'Frozen Onion Rings', quantity: '500 g', synced: true, shared: false },
    { id: '360', name: 'Frozen Chicken Nuggets', quantity: '500 g', synced: true, shared: false },
    { id: '361', name: 'Frozen Fish Sticks', quantity: '500 g', synced: true, shared: false },
    { id: '362', name: 'Frozen Meatballs', quantity: '500 g', synced: true, shared: false },
    { id: '363', name: 'Frozen Dumplings', quantity: '500 g', synced: true, shared: false },
    { id: '364', name: 'Frozen Samosas', quantity: '500 g', synced: true, shared: false },
    { id: '365', name: 'Frozen Spring Rolls', quantity: '500 g', synced: true, shared: false },
    { id: '366', name: 'Ice Cream Sandwiches', quantity: '6 pieces', synced: true, shared: false },
    { id: '367', name: 'Popsicles', quantity: '12 pieces', synced: true, shared: false },
    { id: '368', name: 'Frozen Yogurt', quantity: '500 ml', synced: true, shared: false },
    { id: '369', name: 'Sorbet', quantity: '500 ml', synced: true, shared: false },
    { id: '370', name: 'Gelato', quantity: '500 ml', synced: true, shared: false },
    { id: '371', name: 'Cookies', quantity: '300 g', synced: true, shared: false },
    { id: '372', name: 'Biscuits', quantity: '300 g', synced: true, shared: false },
    { id: '373', name: 'Cake', quantity: '1 piece', synced: true, shared: false },
    { id: '374', name: 'Cupcakes', quantity: '6 pieces', synced: true, shared: false },
    { id: '375', name: 'Muffins', quantity: '6 pieces', synced: true, shared: false },
    { id: '376', name: 'Donuts', quantity: '6 pieces', synced: true, shared: false },
    { id: '377', name: 'Pie', quantity: '1 piece', synced: true, shared: false },
    { id: '378', name: 'Cheesecake', quantity: '1 piece', synced: true, shared: false },
    { id: '379', name: 'Brownies', quantity: '1 tray', synced: true, shared: false },
    { id: '380', name: 'Candy Bars', quantity: '5 pieces', synced: true, shared: false },
    { id: '381', name: 'Gummy Bears', quantity: '200 g', synced: true, shared: false },
    { id: '382', name: 'Lollipops', quantity: '10 pieces', synced: true, shared: false },
    { id: '383', name: 'Mints', quantity: '100 g', synced: true, shared: false },
    { id: '384', name: 'Chewing Gum', quantity: '20 pieces', synced: true, shared: false },
    { id: '385', name: 'Protein Powder', quantity: '500 g', synced: true, shared: false },
    { id: '386', name: 'Vitamins', quantity: '60 tablets', synced: true, shared: false },
    { id: '387', name: 'Supplements', quantity: '60 capsules', synced: true, shared: false },
    { id: '388', name: 'Probiotics', quantity: '30 capsules', synced: true, shared: false },
    { id: '389', name: 'Fiber Supplements', quantity: '60 tablets', synced: true, shared: false },
    { id: '390', name: 'Omega-3 Supplements', quantity: '60 capsules', synced: true, shared: false },
    { id: '391', name: 'Shampoo', quantity: '500 ml', synced: true, shared: false },
    { id: '392', name: 'Conditioner', quantity: '500 ml', synced: true, shared: false },
    { id: '393', name: 'Body Wash', quantity: '500 ml', synced: true, shared: false },
    { id: '394', name: 'Soap', quantity: '4 bars', synced: true, shared: false },
    { id: '395', name: 'Toothpaste', quantity: '2 tubes', synced: true, shared: false },
    { id: '396', name: 'Toothbrush', quantity: '2 pieces', synced: true, shared: false },
    { id: '397', name: 'Mouthwash', quantity: '500 ml', synced: true, shared: false },
    { id: '398', name: 'Floss', quantity: '2 packs', synced: true, shared: false },
    { id: '399', name: 'Deodorant', quantity: '1 piece', synced: true, shared: false },
    { id: '400', name: 'Laundry Detergent', quantity: '1 bottle', synced: true, shared: false },
    { id: '401', name: 'Dish Soap', quantity: '500 ml', synced: true, shared: false },
    { id: '402', name: 'Paper Towels', quantity: '6 rolls', synced: true, shared: false },
    { id: '403', name: 'Toilet Paper', quantity: '12 rolls', synced: true, shared: false },
    { id: '404', name: 'Tissues', quantity: '4 boxes', synced: true, shared: false },
    { id: '405', name: 'Aluminum Foil', quantity: '1 roll', synced: true, shared: false },
    { id: '406', name: 'Plastic Wrap', quantity: '1 roll', synced: true, shared: false },
    { id: '407', name: 'Ziplock Bags', quantity: '1 box', synced: true, shared: false },
    { id: '408', name: 'Garbage Bags', quantity: '1 box', synced: true, shared: false },
    { id: '409', name: 'Candles', quantity: '4 pieces', synced: true, shared: false },
    { id: '410', name: 'Matches', quantity: '2 boxes', synced: true, shared: false },
    { id: '411', name: 'Batteries', quantity: '8 pieces', synced: true, shared: false },
    { id: '412', name: 'Light Bulbs', quantity: '4 pieces', synced: true, shared: false },
    { id: '413', name: 'Pet Food', quantity: '2 Kg', synced: true, shared: false },
    { id: '414', name: 'Cat Litter', quantity: '5 Kg', synced: true, shared: false },
    { id: '415', name: 'Bird Seed', quantity: '1 Kg', synced: true, shared: false },
    { id: '416', name: 'Fish Food', quantity: '200 g', synced: true, shared: false },
    { id: '417', name: 'Baby Food', quantity: '12 jars', synced: true, shared: false },
    { id: '418', name: 'Baby Formula', quantity: '800 g', synced: true, shared: false },
    { id: '419', name: 'Diapers', quantity: '1 pack', synced: true, shared: false },
    { id: '420', name: 'Baby Wipes', quantity: '4 packs', synced: true, shared: false },
    { id: '421', name: 'Seaweed Sheets', quantity: '10 sheets', synced: true, shared: false },
    { id: '422', name: 'Wasabi', quantity: '50 g', synced: true, shared: false },
    { id: '423', name: 'Pickled Ginger', quantity: '100 g', synced: true, shared: false },
    { id: '424', name: 'Miso Paste', quantity: '200 g', synced: true, shared: false },
    { id: '425', name: 'Rice Vinegar', quantity: '250 ml', synced: true, shared: false },
    { id: '426', name: 'Mirin', quantity: '250 ml', synced: true, shared: false },
    { id: '427', name: 'Sake', quantity: '500 ml', synced: true, shared: false },
    { id: '428', name: 'Kimchi', quantity: '300 g', synced: true, shared: false },
    { id: '429', name: 'Gochujang', quantity: '200 g', synced: true, shared: false },
    { id: '430', name: 'Sriracha', quantity: '250 ml', synced: true, shared: false },
    { id: '431', name: 'Harissa', quantity: '200 g', synced: true, shared: false },
    { id: '432', name: 'Chipotle Peppers', quantity: '200 g', synced: true, shared: false },
    { id: '433', name: 'Jalapenos', quantity: '200 g', synced: true, shared: false },
    { id: '434', name: 'Habaneros', quantity: '100 g', synced: true, shared: false },
    { id: '435', name: 'Ghost Peppers', quantity: '50 g', synced: true, shared: false },
    { id: '436', name: 'Saffron', quantity: '5 g', synced: true, shared: false },
    { id: '437', name: 'Star Anise', quantity: '50 g', synced: true, shared: false },
    { id: '438', name: 'Fennel Seeds', quantity: '100 g', synced: true, shared: false },
    { id: '439', name: 'Coriander Seeds', quantity: '100 g', synced: true, shared: false },
    { id: '440', name: 'Mustard Seeds', quantity: '100 g', synced: true, shared: false },
    { id: '441', name: 'Fenugreek', quantity: '100 g', synced: true, shared: false },
    { id: '442', name: 'Asafoetida', quantity: '50 g', synced: true, shared: false },
    { id: '443', name: 'Garam Masala', quantity: '100 g', synced: true, shared: false },
    { id: '444', name: 'Curry Powder', quantity: '100 g', synced: true, shared: false },
    { id: '445', name: 'Chinese Five Spice', quantity: '100 g', synced: true, shared: false },
    { id: '446', name: 'Herbes de Provence', quantity: '50 g', synced: true, shared: false },
    { id: '447', name: 'Italian Seasoning', quantity: '50 g', synced: true, shared: false },
    { id: '448', name: 'Taco Seasoning', quantity: '50 g', synced: true, shared: false },
    { id: '449', name: 'Ranch Seasoning', quantity: '50 g', synced: true, shared: false },
    { id: '450', name: 'Onion Powder', quantity: '100 g', synced: true, shared: false },
    { id: '451', name: 'Garlic Powder', quantity: '100 g', synced: true, shared: false },
    { id: '452', name: 'Celery Salt', quantity: '100 g', synced: true, shared: false },
    { id: '453', name: 'Smoked Paprika', quantity: '100 g', synced: true, shared: false },
    { id: '454', name: 'Cayenne Pepper', quantity: '100 g', synced: true, shared: false },
    { id: '455', name: 'White Pepper', quantity: '100 g', synced: true, shared: false },
    { id: '456', name: 'Pink Peppercorns', quantity: '50 g', synced: true, shared: false },
    { id: '457', name: 'Szechuan Peppercorns', quantity: '50 g', synced: true, shared: false },
    { id: '458', name: 'Sumac', quantity: '100 g', synced: true, shared: false },
    { id: '459', name: 'Za\'atar', quantity: '100 g', synced: true, shared: false },
    { id: '460', name: 'Everything Bagel Seasoning', quantity: '100 g', synced: true, shared: false },
    { id: '461', name: 'Matcha Powder', quantity: '100 g', synced: true, shared: false },
    { id: '462', name: 'Spirulina Powder', quantity: '100 g', synced: true, shared: false },
    { id: '463', name: 'Wheatgrass Powder', quantity: '100 g', synced: true, shared: false },
    { id: '464', name: 'Protein Powder - Vanilla', quantity: '500 g', synced: true, shared: false },
    { id: '465', name: 'Protein Powder - Chocolate', quantity: '500 g', synced: true, shared: false },
    { id: '466', name: 'Protein Powder - Strawberry', quantity: '500 g', synced: true, shared: false },
    { id: '467', name: 'Collagen Powder', quantity: '300 g', synced: true, shared: false },
    { id: '468', name: 'Meal Replacement Shake', quantity: '12 sachets', synced: true, shared: false },
    { id: '469', name: 'Electrolyte Powder', quantity: '30 sachets', synced: true, shared: false },
    { id: '470', name: 'Vitamin C Powder', quantity: '200 g', synced: true, shared: false },
    { id: '471', name: 'Magnesium Powder', quantity: '200 g', synced: true, shared: false },
    { id: '472', name: 'Calcium Powder', quantity: '200 g', synced: true, shared: false },
    { id: '473', name: 'Iron Supplements', quantity: '60 tablets', synced: true, shared: false },
    { id: '474', name: 'Zinc Supplements', quantity: '60 tablets', synced: true, shared: false },
    { id: '475', name: 'Vitamin D3', quantity: '60 tablets', synced: true, shared: false },
    { id: '476', name: 'Vitamin B12', quantity: '60 tablets', synced: true, shared: false },
    { id: '477', name: 'Multivitamins', quantity: '60 tablets', synced: true, shared: false },
    { id: '478', name: 'Prenatal Vitamins', quantity: '60 tablets', synced: true, shared: false },
    { id: '479', name: 'Melatonin', quantity: '60 tablets', synced: true, shared: false },
    { id: '480', name: 'Turmeric Supplements', quantity: '60 capsules', synced: true, shared: false },
    { id: '481', name: 'Ginger Supplements', quantity: '60 capsules', synced: true, shared: false },
    { id: '500', name: 'Laundry Detergent', quantity: '1 bottle', synced: true, shared: false },
    { id: '501', name: 'Dish Soap', quantity: '500 ml', synced: true, shared: false },
    { id: '502', name: 'Paper Towels', quantity: '6 rolls', synced: true, shared: false },
    { id: '503', name: 'Toilet Paper', quantity: '12 rolls', synced: true, shared: false },
    { id: '504', name: 'Tissues', quantity: '4 boxes', synced: true, shared: false },
    { id: '505', name: 'Aluminum Foil', quantity: '1 roll', synced: true, shared: false },
    { id: '506', name: 'Plastic Wrap', quantity: '1 roll', synced: true, shared: false },
    { id: '507', name: 'Ziplock Bags', quantity: '1 box', synced: true, shared: false },
    { id: '508', name: 'Garbage Bags', quantity: '1 box', synced: true, shared: false },
    { id: '509', name: 'Candles', quantity: '4 pieces', synced: true, shared: false },
    { id: '510', name: 'Matches', quantity: '2 boxes', synced: true, shared: false },
    { id: '511', name: 'Batteries', quantity: '8 pieces', synced: true, shared: false },
    { id: '512', name: 'Light Bulbs', quantity: '4 pieces', synced: true, shared: false },
    { id: '513', name: 'Pet Food', quantity: '2 Kg', synced: true, shared: false },
    { id: '514', name: 'Cat Litter', quantity: '5 Kg', synced: true, shared: false },
    { id: '515', name: 'Bird Seed', quantity: '1 Kg', synced: true, shared: false },
    { id: '516', name: 'Fish Food', quantity: '200 g', synced: true, shared: false },
    { id: '517', name: 'Baby Food', quantity: '12 jars', synced: true, shared: false },
    { id: '518', name: 'Baby Formula', quantity: '800 g', synced: true, shared: false },
    { id: '519', name: 'Diapers', quantity: '1 pack', synced: true, shared: false },
    { id: '520', name: 'Baby Wipes', quantity: '4 packs', synced: true, shared: false },
    { id: '521', name: 'Seaweed Sheets', quantity: '10 sheets', synced: true, shared: false },
    { id: '522', name: 'Wasabi', quantity: '50 g', synced: true, shared: false },
    { id: '523', name: 'Pickled Ginger', quantity: '100 g', synced: true, shared: false },
    { id: '524', name: 'Miso Paste', quantity: '200 g', synced: true, shared: false },
    { id: '525', name: 'Rice Vinegar', quantity: '250 ml', synced: true, shared: false },
    { id: '526', name: 'Mirin', quantity: '250 ml', synced: true, shared: false },
    { id: '527', name: 'Sake', quantity: '500 ml', synced: true, shared: false },
    { id: '528', name: 'Kimchi', quantity: '300 g', synced: true, shared: false },
    { id: '529', name: 'Gochujang', quantity: '200 g', synced: true, shared: false },
    { id: '530', name: 'Sriracha', quantity: '250 ml', synced: true, shared: false },
    { id: '531', name: 'Harissa', quantity: '200 g', synced: true, shared: false },
    { id: '532', name: 'Chipotle Peppers', quantity: '200 g', synced: true, shared: false },
    { id: '533', name: 'Jalapenos', quantity: '200 g', synced: true, shared: false },
    { id: '534', name: 'Habaneros', quantity: '100 g', synced: true, shared: false },
    { id: '535', name: 'Ghost Peppers', quantity: '50 g', synced: true, shared: false },
    { id: '536', name: 'Saffron', quantity: '5 g', synced: true, shared: false },
    { id: '537', name: 'Star Anise', quantity: '50 g', synced: true, shared: false },
    { id: '538', name: 'Fennel Seeds', quantity: '100 g', synced: true, shared: false },
    { id: '539', name: 'Coriander Seeds', quantity: '100 g', synced: true, shared: false },
    { id: '540', name: 'Mustard Seeds', quantity: '100 g', synced: true, shared: false },
    { id: '541', name: 'Fenugreek', quantity: '100 g', synced: true, shared: false },
    { id: '542', name: 'Asafoetida', quantity: '50 g', synced: true, shared: false },
    { id: '543', name: 'Garam Masala', quantity: '100 g', synced: true, shared: false },
    { id: '544', name: 'Curry Powder', quantity: '100 g', synced: true, shared: false },
    { id: '545', name: 'Chinese Five Spice', quantity: '100 g', synced: true, shared: false },
    { id: '546', name: 'Herbes de Provence', quantity: '50 g', synced: true, shared: false },
    { id: '547', name: 'Italian Seasoning', quantity: '50 g', synced: true, shared: false },
    { id: '548', name: 'Taco Seasoning', quantity: '50 g', synced: true, shared: false },
    { id: '549', name: 'Ranch Seasoning', quantity: '50 g', synced: true, shared: false },
    { id: '550', name: 'Onion Powder', quantity: '100 g', synced: true, shared: false },
    { id: '551', name: 'Garlic Powder', quantity: '100 g', synced: true, shared: false },
    { id: '552', name: 'Celery Salt', quantity: '100 g', synced: true, shared: false },
    { id: '553', name: 'Smoked Paprika', quantity: '100 g', synced: true, shared: false },
    { id: '554', name: 'Cayenne Pepper', quantity: '100 g', synced: true, shared: false },
    { id: '555', name: 'White Pepper', quantity: '100 g', synced: true, shared: false },
    { id: '556', name: 'Pink Peppercorns', quantity: '50 g', synced: true, shared: false },
    { id: '557', name: 'Szechuan Peppercorns', quantity: '50 g', synced: true, shared: false },
    { id: '558', name: 'Sumac', quantity: '100 g', synced: true, shared: false },
    { id: '559', name: 'Za\'atar', quantity: '100 g', synced: true, shared: false },
    { id: '560', name: 'Everything Bagel Seasoning', quantity: '100 g', synced: true, shared: false },
    { id: '561', name: 'Matcha Powder', quantity: '100 g', synced: true, shared: false },
    { id: '562', name: 'Spirulina Powder', quantity: '100 g', synced: true, shared: false },
    { id: '563', name: 'Wheatgrass Powder', quantity: '100 g', synced: true, shared: false },
    { id: '564', name: 'Protein Powder - Vanilla', quantity: '500 g', synced: true, shared: false },
    { id: '565', name: 'Protein Powder - Chocolate', quantity: '500 g', synced: true, shared: false },
    { id: '566', name: 'Protein Powder - Strawberry', quantity: '500 g', synced: true, shared: false },
    { id: '567', name: 'Collagen Powder', quantity: '300 g', synced: true, shared: false },
    { id: '568', name: 'Meal Replacement Shake', quantity: '12 sachets', synced: true, shared: false },
    { id: '569', name: 'Electrolyte Powder', quantity: '30 sachets', synced: true, shared: false },
    { id: '570', name: 'Vitamin C Powder', quantity: '200 g', synced: true, shared: false },
    { id: '571', name: 'Magnesium Powder', quantity: '200 g', synced: true, shared: false },
    { id: '572', name: 'Calcium Powder', quantity: '200 g', synced: true, shared: false },
    { id: '573', name: 'Iron Supplements', quantity: '60 tablets', synced: true, shared: false },
    { id: '574', name: 'Zinc Supplements', quantity: '60 tablets', synced: true, shared: false },
    { id: '575', name: 'Vitamin D3', quantity: '60 tablets', synced: true, shared: false },
    { id: '576', name: 'Vitamin B12', quantity: '60 tablets', synced: true, shared: false },
    { id: '577', name: 'Multivitamins', quantity: '60 tablets', synced: true, shared: false },
    { id: '578', name: 'Prenatal Vitamins', quantity: '60 tablets', synced: true, shared: false },
    { id: '579', name: 'Melatonin', quantity: '60 tablets', synced: true, shared: false },
    { id: '580', name: 'Turmeric Supplements', quantity: '60 capsules', synced: true, shared: false },
    { id: '581', name: 'Ginger Supplements', quantity: '60 capsules', synced: true, shared: false },
];